In [3]:
import keras 
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, AveragePooling2D
from keras import backend as K 
import numpy as np

Using TensorFlow backend.


In [4]:
img_rows, img_cols = 28,28
(x_train, y_train), (x_test,y_test) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
x_test.shape

(10000, 28, 28)

In [7]:
y_train.shape

(60000,)

In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows,img_cols,1)
x_test = x_test.reshape(x_test.shape[0], img_rows,img_cols,1)
input_shape = (img_rows, img_cols, 1) 

In [9]:
x_train.shape

(60000, 28, 28, 1)

In [10]:
x_train.dtype 

dtype('uint8')

In [0]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /=255

In [12]:
x_train.dtype

dtype('float32')

In [13]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [0]:
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [16]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [17]:
y_train.shape

(60000, 10)

In [18]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [19]:
model = Sequential()
model.add(Conv2D(32, kernel_size =(3,3), input_shape=input_shape))
model.add(Conv2D(64, kernel_size =(3,3)))
model.add(AveragePooling2D(pool_size = (3,3)))
model.add(Dropout(0.25)) #25percent is zero
model.add(Flatten())
model.add(Dense(128, activation = 'sigmoid'))
model.add(Dropout(0.5))
model.add(Dense(10, activation = 'sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [20]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
average_pooling2d_1 (Average (None, 8, 8, 64)          0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 8, 8, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 4096)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               524416    
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
__________

In [0]:
model.compile(loss = keras.losses.categorical_crossentropy,optimizer =keras.optimizers.SGD(), metrics = ['accuracy'])

In [22]:
model.fit(x_train, y_train, batch_size =128, #128 pictures videokarta prinimayet 128, uskorit process 
         epochs = 12, verbose =1, validation_data = (x_test, y_test))

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 11s 186us/step - loss: 2.3345 - acc: 0.1089 - val_loss: 2.2758 - val_acc: 0.1076
Epoch 2/12
60000/60000 [==============================] - 6s 105us/step - loss: 2.2548 - acc: 0.1641 - val_loss: 2.1252 - val_acc: 0.5665
Epoch 3/12
60000/60000 [==============================] - 6s 105us/step - loss: 1.7297 - acc: 0.4805 - val_loss: 1.0749 - val_acc: 0.8187
Epoch 4/12
60000/60000 [==============================] - 6s 105us/step - loss: 1.0041 - acc: 0.7312 - val_loss: 0.6009 - val_acc: 0.8723
Epoch 5/12
60000/60000 [==============================] - 6s 105us/step - loss: 0.7197 - acc: 0.8043 - val_loss: 0.4505 - val_acc: 0.8938
Epoch 6/12
60000/60000 [==============================] - 6s 105us/step - loss: 0.5966 - acc: 0.8374 - val_loss: 0.3809 - val_acc: 0.9032
Epoch 7/12
60000/60000 [==============================] - 6s 105us/step -